allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis@4.0.5-alpha.1'
  - '@deepseek-ai/dsh-client-connection@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-locale@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-layout@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-plugin-manager@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-renderer@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-settings@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-sidebar@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-slots@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-settings@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-workspace@0.2.1-alpha.1'
  - '@deepseek-ai/schemastery@3.18.5-alpha.1'
