export const STYLE_ID = 'dsh-git-workspace/client.css'

export const STYLES = String.raw`
.dgw-view,.dgw-settings-card{--dgw-bg:var(--dsw-alias-bg-base,#f6f7f9);--dgw-panel:var(--dsw-alias-bg-layer-1,#fff);--dgw-border:var(--dsw-alias-border-l2,#dfe3e8);--dgw-text:var(--dsw-alias-label-primary,#17212b);--dgw-muted:var(--dsw-alias-label-secondary,#66727f);--dgw-accent:#167d66;--dgw-accent-soft:#e8f5f1;--dgw-danger:#b42318;--dgw-warning:#b54708;--dgw-neutral:#eef1f4;--dgw-danger-bg:#fff0ed;--dgw-info:#175cd3;--dgw-info-bg:#edf4ff;--dgw-add:#146c43;--dgw-add-bg:#e9f8f0}
body[data-ds-dark-theme] .dgw-view,body[data-ds-dark-theme] .dgw-settings-card{--dgw-accent:#65d6b7;--dgw-accent-soft:#163d35;--dgw-danger:#ffaaa0;--dgw-warning:#f8be70;--dgw-neutral:#303540;--dgw-danger-bg:#492724;--dgw-info:#9ec5ff;--dgw-info-bg:#223652;--dgw-add:#8ee0b3;--dgw-add-bg:#183c2d}
.dgw-view{position:relative;height:100%;min-height:0;min-width:0;overflow:hidden;background:var(--dgw-bg)}
.dgw-shell{height:100%;display:grid;grid-template-rows:auto auto auto minmax(0,1fr);color:var(--dgw-text);background:var(--dgw-bg);font:13px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.dgw-shell button,.dgw-shell select,.dgw-shell textarea,.dgw-shell input{font:inherit}.dgw-shell button{border:1px solid var(--dgw-border);background:var(--dgw-panel);color:inherit;border-radius:7px;padding:6px 10px;cursor:pointer}.dgw-shell button:hover:not(:disabled){border-color:var(--dgw-accent);color:var(--dgw-accent)}.dgw-shell button:disabled{opacity:.45;cursor:not-allowed}
.dgw-topbar{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 18px;border-bottom:1px solid var(--dgw-border);background:var(--dgw-panel)}.dgw-topbar>div:first-child{display:flex;align-items:baseline;gap:10px}.dgw-topbar strong{font-size:16px}.dgw-subtitle{color:var(--dgw-muted)}.dgw-top-actions{display:flex;align-items:center;gap:8px}.dgw-top-actions select{min-width:170px;border:1px solid var(--dgw-border);border-radius:7px;padding:6px 8px;background:var(--dgw-panel);color:inherit}.dgw-close{margin-left:4px}
.dgw-alert{display:flex;align-items:center;justify-content:space-between;background:var(--dgw-danger-bg);color:var(--dgw-danger);border-bottom:1px solid var(--dgw-border);padding:8px 16px}.dgw-alert button{padding:2px 7px}.dgw-batchbar{display:flex;align-items:center;gap:8px;padding:8px 16px;border-bottom:1px solid var(--dgw-border);background:var(--dgw-panel)}.dgw-batchbar span{color:var(--dgw-muted);margin-right:auto}
.dgw-columns{display:grid;grid-template-columns:minmax(210px,24%) minmax(360px,1fr) minmax(240px,30%);min-height:0;overflow:hidden}.dgw-repos,.dgw-main,.dgw-detail{min-width:0;min-height:0;background:var(--dgw-panel)}.dgw-repos{border-right:1px solid var(--dgw-border);overflow:auto}.dgw-detail{border-left:1px solid var(--dgw-border);overflow:auto}.dgw-main{overflow:auto}.dgw-section-head{position:sticky;top:0;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px 12px;border-bottom:1px solid var(--dgw-border);background:var(--dgw-panel);font-weight:600}.dgw-section-head button{padding:2px 7px;font-size:12px}.dgw-empty,.dgw-placeholder{color:var(--dgw-muted);padding:24px}.dgw-repos ul,.dgw-change-list ul{list-style:none;margin:0;padding:0}.dgw-repo{display:grid;grid-template-columns:24px 1fr;border-bottom:1px solid var(--dgw-border)}.dgw-repo.active{background:var(--dgw-accent-soft);box-shadow:inset 3px 0 var(--dgw-accent)}.dgw-repo>input{margin:14px 0 0 10px}.dgw-repo>button{display:flex;flex-direction:column;align-items:stretch;gap:3px;border:0;border-radius:0;background:transparent;padding:11px 12px 11px 6px;text-align:left}.dgw-repo-title{display:flex;justify-content:space-between;gap:8px}.dgw-repo-title code{color:var(--dgw-muted);font-size:11px}.dgw-repo-path{color:var(--dgw-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px}.dgw-status{color:var(--dgw-accent);font-size:12px}.dgw-status.danger{color:var(--dgw-danger)}
.dgw-repo-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 16px;border-bottom:1px solid var(--dgw-border)}.dgw-repo-head>div:first-child{display:flex;flex-direction:column}.dgw-repo-head span{color:var(--dgw-muted);font-size:12px}.dgw-network-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.dgw-branch-menu{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;padding:10px 16px;background:var(--dgw-bg);border-bottom:1px solid var(--dgw-border)}.dgw-branch-switch{grid-column:1/-1;display:grid;grid-template-columns:auto minmax(160px,1fr) auto;align-items:center;gap:8px}.dgw-branch-switch label{color:var(--dgw-muted);font-weight:600}.dgw-branch-switch select{min-width:0;border:1px solid var(--dgw-border);border-radius:7px;padding:6px 8px;background:var(--dgw-panel);color:inherit}.dgw-branch-list{min-width:0;display:flex;align-items:center;gap:6px;overflow:auto}.dgw-branch-item{flex:0 0 auto;display:inline-flex;align-items:center;border:1px solid var(--dgw-border);border-radius:7px;background:var(--dgw-panel);overflow:hidden}.dgw-branch-item>span{max-width:180px;padding:5px 8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dgw-branch-item button{border:0;border-left:1px solid var(--dgw-border);border-radius:0;color:var(--dgw-danger);padding:5px 7px}.dgw-tabs{display:flex;border-bottom:1px solid var(--dgw-border);padding:0 12px}.dgw-tabs button{border:0;border-radius:0;background:transparent;padding:10px 12px;border-bottom:2px solid transparent}.dgw-tabs button.active{color:var(--dgw-accent);border-bottom-color:var(--dgw-accent)}
.dgw-changes{padding:12px}.dgw-commit-box{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:12px}.dgw-commit-box textarea{resize:vertical;min-height:58px;border:1px solid var(--dgw-border);border-radius:7px;padding:8px;background:var(--dgw-panel);color:inherit}.dgw-commit-box button{background:var(--dgw-accent);border-color:var(--dgw-accent);color:var(--dgw-panel)}.dgw-list-title{display:flex;align-items:center;justify-content:space-between;padding:7px 4px;color:var(--dgw-muted);font-weight:600}.dgw-list-title button{border:0;padding:2px 6px}.dgw-file{display:flex;align-items:center;border-top:1px solid var(--dgw-border)}.dgw-file-main{flex:1;min-width:0;display:flex;gap:9px;align-items:center!important;border:0!important;border-radius:0!important;padding:7px 5px!important;text-align:left;background:transparent!important}.dgw-change{display:inline-grid;place-items:center;width:18px;height:18px;border-radius:4px;background:var(--dgw-neutral);color:var(--dgw-muted);font-weight:700;font-size:11px}.dgw-conflict{background:var(--dgw-danger-bg);color:var(--dgw-danger)}.dgw-untracked,.dgw-added{background:var(--dgw-accent-soft);color:var(--dgw-accent)}.dgw-file-path{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dgw-icon-button{border:0!important;background:transparent!important;font-size:17px;padding:4px 10px!important}
.dgw-history{list-style:none;margin:0;padding:8px 16px}.dgw-history li{border-bottom:1px solid var(--dgw-border)}.dgw-history li>button{width:100%;display:grid;grid-template-columns:66px minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px 0;border:0;border-radius:0;background:transparent;text-align:left}.dgw-history code{color:var(--dgw-accent)}.dgw-history li>button>div{display:flex;flex-direction:column;min-width:0}.dgw-history strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dgw-history span{color:var(--dgw-muted);font-size:12px}.dgw-history-open{white-space:nowrap}.dgw-remotes{padding:12px}.dgw-remotes article{border:1px solid var(--dgw-border);border-radius:9px;padding:10px;margin-bottom:10px}.dgw-remote-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.dgw-remote-head>span{display:flex;flex-wrap:wrap;justify-content:flex-end}.dgw-remote-head button{padding:2px 7px;color:var(--dgw-danger)}.dgw-remote-row{display:grid;grid-template-columns:auto minmax(0,1fr);gap:5px 8px;align-items:center;margin:9px 0}.dgw-remote-row>span{font-weight:600;color:var(--dgw-muted)}.dgw-remote-row>.dgw-policy{justify-self:end}.dgw-remote-row>code{grid-column:1/-1;min-width:0;white-space:normal;overflow-wrap:anywhere;color:var(--dgw-text)}.dgw-remotes small,.dgw-hint{color:var(--dgw-muted)}.dgw-remotes .dgw-hint{display:block;width:100%;margin:12px 0 0;line-height:1.6;overflow-wrap:anywhere}.dgw-policy{font-style:normal;padding:2px 6px;border-radius:999px;background:var(--dgw-neutral)}.dgw-policy.proxy{background:var(--dgw-info-bg);color:var(--dgw-info)}.dgw-policy.direct{background:var(--dgw-accent-soft);color:var(--dgw-accent)}.dgw-policy.block{background:var(--dgw-danger-bg);color:var(--dgw-danger)}
.dgw-diff{min-width:100%;width:max-content;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.dgw-diff-line{display:grid;grid-template-columns:46px 46px minmax(320px,1fr);min-height:20px}.dgw-diff-line>span{padding:1px 8px;text-align:right;color:var(--dgw-muted);border-right:1px solid var(--dgw-border);user-select:none}.dgw-diff-line>code{display:block;padding:1px 10px;white-space:pre}.dgw-diff-line.meta>code{color:var(--dgw-muted);font-weight:600}.dgw-diff-line.hunk{background:var(--dgw-info-bg);color:var(--dgw-info)}.dgw-diff-line.hunk>code{font-weight:600}.dgw-diff-line.addition{background:var(--dgw-add-bg)}.dgw-diff-line.addition>code{color:var(--dgw-add)}.dgw-diff-line.deletion{background:var(--dgw-danger-bg)}.dgw-diff-line.deletion>code{color:var(--dgw-danger)}.dgw-diff-line.note>code{color:var(--dgw-warning);font-style:italic}.dgw-diff-empty{padding:18px;color:var(--dgw-muted)}.dgw-commit-detail{padding:16px}.dgw-commit-detail>pre{margin:0 0 16px;white-space:pre-wrap;overflow-wrap:anywhere;font:600 13px/1.55 ui-sans-serif,system-ui,sans-serif}.dgw-commit-detail dl{margin:0}.dgw-commit-detail dl>div{display:grid;grid-template-columns:54px minmax(0,1fr);gap:8px;margin:7px 0}.dgw-commit-detail dt{color:var(--dgw-muted)}.dgw-commit-detail dd{min-width:0;margin:0;overflow-wrap:anywhere}.dgw-commit-detail dd code{display:inline-block;max-width:100%;overflow:hidden;text-overflow:ellipsis;vertical-align:bottom}.dgw-commit-detail dd code+code{margin-left:6px}.dgw-commit-detail h3{font-size:13px;margin:18px 0 6px}.dgw-commit-detail ul{list-style:none;margin:0;padding:0}.dgw-commit-detail li{display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px;align-items:center;padding:7px 0;border-top:1px solid var(--dgw-border)}.dgw-commit-detail li code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dgw-commit-file-status{min-width:42px;padding:2px 6px;border-radius:5px;text-align:center;background:var(--dgw-neutral);color:var(--dgw-muted);font-size:11px}.dgw-commit-file-status.status-a{background:var(--dgw-accent-soft);color:var(--dgw-accent)}.dgw-commit-file-status.status-d{background:var(--dgw-danger-bg);color:var(--dgw-danger)}.dgw-operation-empty,.dgw-results{padding:16px}.dgw-operation-empty p{color:var(--dgw-muted)}.dgw-results>div{display:flex;flex-direction:column;padding:9px 0;border-top:1px solid var(--dgw-border)}.dgw-results .ok strong{color:var(--dgw-accent)}.dgw-results .failed strong{color:var(--dgw-danger)}.dgw-results span{color:var(--dgw-muted)}
.dgw-settings-card{list-style:none;border:1px solid var(--dgw-border);border-radius:10px;background:var(--dgw-panel);color:var(--dgw-text);overflow:hidden}.dgw-settings-card summary{display:flex;justify-content:space-between;align-items:center;cursor:pointer;padding:14px 16px}.dgw-settings-card summary>span:first-child{display:flex;flex-direction:column}.dgw-settings-card summary small{color:var(--dgw-muted);font-weight:400}.dgw-settings-body{border-top:1px solid var(--dgw-border);padding:14px 16px;display:flex;flex-direction:column;gap:13px}.dgw-settings-body label{display:flex;flex-direction:column;gap:5px;font-weight:600}.dgw-settings-body input,.dgw-settings-body textarea,.dgw-settings-body select{border:1px solid var(--dgw-border);border-radius:7px;padding:8px;background:var(--dgw-panel);color:inherit;font:inherit}.dgw-settings-body textarea{resize:vertical;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-weight:400}.dgw-settings-body label small{color:var(--dgw-muted);font-weight:400}.dgw-settings-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.dgw-settings-order{color:var(--dgw-muted);margin:0}.dgw-settings-notice{color:var(--dgw-accent);margin:0}.dgw-settings-actions{display:flex;justify-content:flex-end;gap:8px}.dgw-settings-actions button{border:1px solid var(--dgw-border);background:var(--dgw-panel);border-radius:7px;padding:7px 11px;color:inherit}.dgw-settings-actions .primary{background:var(--dgw-accent);border-color:var(--dgw-accent);color:var(--dgw-panel)}.dgw-settings-actions .danger{color:var(--dgw-danger);margin-right:auto}
.dgw-modal-backdrop{position:absolute;inset:0;z-index:20;display:grid;place-items:center;padding:24px;background:rgba(12,20,28,.42)}.dgw-modal{width:min(680px,100%);max-height:min(720px,90%);display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:var(--dgw-panel);border:1px solid var(--dgw-border);border-radius:12px;box-shadow:0 20px 60px rgba(0,0,0,.22);overflow:hidden}.dgw-modal header,.dgw-modal footer{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:14px 16px;border-bottom:1px solid var(--dgw-border)}.dgw-modal header>div{display:flex;flex-direction:column}.dgw-modal header span{color:var(--dgw-muted)}.dgw-modal header button{border:0;font-size:20px}.dgw-modal footer{justify-content:flex-end;border:0;border-top:1px solid var(--dgw-border)}.dgw-modal footer .primary{background:var(--dgw-accent);border-color:var(--dgw-accent);color:var(--dgw-panel)}.dgw-plan-list{overflow:auto;padding:6px 16px}.dgw-plan-list>div{display:grid;grid-template-columns:60px minmax(100px,1fr) 100px minmax(180px,2fr);gap:9px;align-items:center;padding:10px 0;border-bottom:1px solid var(--dgw-border)}.dgw-plan-list span{font-size:12px}.dgw-plan-list .ready{color:var(--dgw-accent)}.dgw-plan-list .blocked{color:var(--dgw-danger)}.dgw-plan-list small{color:var(--dgw-muted)}
.dgw-columns{display:flex;grid-template-columns:none}.dgw-repos{flex:0 0 var(--dgw-repo-width,240px);border:0}.dgw-main{flex:1 1 0}.dgw-detail{flex:0 0 clamp(300px,var(--dgw-detail-width,520px),calc(100% - var(--dgw-repo-width,240px) - 340px));border:0}.dgw-splitter{position:relative;z-index:3;flex:0 0 7px;cursor:col-resize;touch-action:none;background:var(--dgw-bg);outline:none}.dgw-splitter:after{content:'';position:absolute;inset:0 auto 0 3px;width:1px;background:var(--dgw-border)}.dgw-splitter:hover:after,.dgw-splitter:focus-visible:after{left:2px;width:3px;background:var(--dgw-accent)}
.dgw-commit-detail li{display:block;padding:0}.dgw-commit-detail li>button{width:100%;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:8px;align-items:center;padding:7px 0;border:0;border-radius:0;background:transparent;text-align:left}.dgw-commit-detail li>button code{min-width:0}.dgw-commit-file-open{color:var(--dgw-accent);font-size:12px;white-space:nowrap}
.dgw-plan-list>div{grid-template-columns:minmax(120px,1fr) 100px minmax(160px,2fr) 70px}.dgw-plan-list span{justify-self:end;font-weight:700}.dgw-plan-list .pending{color:var(--dgw-muted)}.dgw-plan-list .running{color:var(--dgw-info)}.dgw-plan-list .success{color:var(--dgw-accent)}.dgw-plan-list .failed,.dgw-plan-list .blocked{color:var(--dgw-danger)}.dgw-plan-list small{overflow-wrap:anywhere}
@media(max-width:1000px){.dgw-settings-grid{grid-template-columns:1fr}}
@media(max-width:720px){.dgw-topbar{align-items:flex-start}.dgw-subtitle{display:none}.dgw-top-actions{flex-wrap:wrap;justify-content:flex-end}.dgw-top-actions select{min-width:120px}.dgw-columns{display:block}.dgw-repos,.dgw-splitter{display:none}.dgw-main{height:100%}.dgw-detail{position:absolute;inset:150px 0 0;width:100%;box-shadow:-8px 0 30px rgba(0,0,0,.12)}.dgw-batchbar{display:none}.dgw-network-actions button:nth-child(1){display:none}.dgw-commit-box{grid-template-columns:1fr}.dgw-branch-menu{grid-template-columns:1fr auto}.dgw-branch-switch{grid-template-columns:1fr auto}.dgw-branch-switch label{grid-column:1/-1}.dgw-plan-list>div{grid-template-columns:minmax(100px,1fr) 70px}.dgw-plan-list small{grid-column:1/-1}.dgw-close{font-size:0}.dgw-close:after{content:'关闭';font-size:13px}}
`

export function injectStyles(): () => void {
  const existing = document.querySelector<HTMLStyleElement>(`style[data-plugin-css=${JSON.stringify(STYLE_ID)}]`)
  if (existing !== null) return () => {}
  const tag = document.createElement('style')
  tag.dataset.plugin = 'dsh-git-workspace'
  tag.dataset.pluginCss = STYLE_ID
  tag.textContent = STYLES
  document.head.appendChild(tag)
  return () => { tag.remove() }
}
